
article:
  auto_cover: false
  type: story

menubar:
  columns: 4
  items:
    - id: home
      theme: '#FFFFFF'
      title: 主页
      icon:
      url: /
    - id: family
      theme: '#18CDFC'
      title: 成员
      icon: ''
      url: /family/
    - id: timeline
      theme: '#3DC550'
      title: 时间线
      icon: ''
      url: /timeline/
    - id: about
      theme: '#F44336'
      title: 关于
      icon: ''
      url: /about/
    - id: resources
      theme: '#FF9800'
      title: 资源
      icon: ''
      url: /resources/
logo:
  subtitle: '定位人生，瞄准方向 | 自我挑战，共创辉煌'

site_tree:
  home:
    leftbar: ghuser
    rightbar: 
  post:
    menu_id: post
    leftbar: ghuser
    rightbar:
  family:
    menu_id: family
    leftbar: ghuser
    rightbar:

